### ISSUE TITLE
Example Request: Covid-19 Mobile App

### ISSUE THREAD

**Issue by mehdi1514** [nisrulz/flutter-examples#70]
Hey Nishant,

I would like to contribute to this repo. I have created a mobile app that tracks Covid-19 cases. It uses the NovelCOVID API to fetch the results. I have also included some data visualizations in the app.

**Comment by nisrulz** [comment]
Great! Thank you for opening this issue.

Ok, first a few things:
- Read the contribution guidelines in readme. Package name needs to be in a certain way so that all apps use same pattern.
- The example app as you describe needs to be built in a way it is easily consumable. i.e split your code into files. Having one single main.dart file with a lot of nesting is not readable and also hard to review.
- Make sure you are using the latest version of Flutter.
- The libs you want to use can you list them down here? So I can take a look at what they are.

**Comment by mehdi1514** [comment]
I have changed the package name according to the guidelines. The package name in the case of this example app is github.nisrulz.<the app name here>

I have split the code into different files. I will document the code and also use understandable variable names as much as possible. I have also formatted the code in every file.

I am using the latest version of flutter viz. v 1.22.0

The packages used in this project are as follows:
1. number_display - to display data in a width-limited component. For eg: it converts 2500000 to 2.5M
2. http - to send HTTP requests to the API
3. bezier_chart - to visualize the received data from the API
4. folding_cell - to display a foldable cell to view details(total deaths, today cases, etc.). This foldable cell is present in the 'Affected Countries' page.

There is a requirement to use the API because without the API, it is not possible to get the data(total deaths, today deaths, total cases, active cases, etc.).

**Comment by nisrulz** [comment]
Looks good to me. 

I think you are good to open the PR. Make sure you branch from `develop`, add all your changes and then open your PR against `develop`.

**Comment by mehdi1514** [comment]
I have opened the PR. Please if you could review it.

**Comment by nisrulz** [comment]
PR #73 was merged. Closing the issue.
